name: Auto-update

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

defaults:
  run:
    shell: bash -euxo pipefail {0}

jobs:
  update:
    runs-on: macos-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v5
      - uses: Homebrew/actions/setup-homebrew@master
      - uses: Homebrew/actions/git-user-config@master
      - name: Update packages
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "GitHub Actions"
          brew tap ${{ github.repository }}
          for formula in Formula/*.rb; do
            package=$(basename "${formula:?}" .rb)
            for version in $(brew livecheck --quiet --newer-only --json "${{ github.repository }}/${package}" | jq -r '.[].version.latest'); do
              gh pr list --search "${package}: update" --state open --json number | jq -e '.[] | select(.number)' >/dev/null && continue
              git checkout -b "bump-${package}-${version}"
              brew bump-formula-pr --write-only --commit --version="${version:?}" "${{ github.repository }}/${package:?}"
              git push origin "bump-${package}-${version}"
              gh pr create --title "${package}: update to ${version}" --body "Automated update of ${package} to version ${version}"
              git checkout ${{ github.ref }}
            done
          done
