name: Tests

on:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash -euxo pipefail {0}

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - uses: Homebrew/actions/setup-homebrew@master
      - name: Test formulas
        run: |
          for formula in Formula/*.rb; do
            package=$(basename "$formula" .rb)
            brew install --build-bottle "$formula"
            brew test "$formula"
            brew audit --strict "$formula"
          done
